# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.AccountIntegration do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :categories,
    :image,
    :square_image,
    :color,
    :slug
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :categories => [MergeAccountingClient.Model.CategoriesEnum.t()] | nil,
          :image => String.t() | nil,
          :square_image => String.t() | nil,
          :color => String.t() | nil,
          :slug => String.t() | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.AccountIntegration do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:categories, :list, MergeAccountingClient.Model.CategoriesEnum, options)
  end
end
