# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.AccountToken do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :account_token,
    :integration
  ]

  @type t :: %__MODULE__{
          :account_token => String.t(),
          :integration => MergeAccountingClient.Model.AccountIntegration.t()
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.AccountToken do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:integration, :struct, MergeAccountingClient.Model.AccountIntegration, options)
  end
end
