# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.AccountDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :integration,
    :integration_slug,
    :category,
    :end_user_origin_id,
    :end_user_organization_name,
    :end_user_email_address,
    :status,
    :webhook_listener_url
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :integration => String.t() | nil,
          :integration_slug => String.t() | nil,
          :category => CategoryEnum | nil,
          :end_user_origin_id => String.t() | nil,
          :end_user_organization_name => String.t() | nil,
          :end_user_email_address => String.t() | nil,
          :status => String.t() | nil,
          :webhook_listener_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.AccountDetails do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:category, :struct, MergeAccountingClient.Model.CategoryEnum, options)
  end
end
