# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.AvailableActions do
  @moduledoc """
  # The AvailableActions Object ### Description The `Activity` object is used to see all available model/operation combinations for an integration.  ### Usage Example Fetch all the actions available for the `Zenefits` integration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :integration,
    :passthrough_available,
    :available_model_operations
  ]

  @type t :: %__MODULE__{
          :integration => MergeAccountingClient.Model.AccountIntegration.t(),
          :passthrough_available => boolean(),
          :available_model_operations => [MergeAccountingClient.Model.ModelOperation.t()] | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.AvailableActions do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:integration, :struct, MergeAccountingClient.Model.AccountIntegration, options)
    |> deserialize(
      :available_model_operations,
      :list,
      MergeAccountingClient.Model.ModelOperation,
      options
    )
  end
end
