# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.DebugModeLog do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :log_id,
    :dashboard_view,
    :log_summary
  ]

  @type t :: %__MODULE__{
          :log_id => String.t(),
          :dashboard_view => String.t(),
          :log_summary => MergeAccountingClient.Model.DebugModelLogSummary.t()
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.DebugModeLog do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :log_summary,
      :struct,
      MergeAccountingClient.Model.DebugModelLogSummary,
      options
    )
  end
end
