# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.ErrorValidationProblem do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :source,
    :title,
    :detail,
    :problem_type
  ]

  @type t :: %__MODULE__{
          :source => MergeAccountingClient.Model.ValidationProblemSource.t() | nil,
          :title => String.t(),
          :detail => String.t(),
          :problem_type => String.t()
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.ErrorValidationProblem do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:source, :struct, MergeAccountingClient.Model.ValidationProblemSource, options)
  end
end
