# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.IgnoreCommonModel do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :reason,
    :message
  ]

  @type t :: %__MODULE__{
          :reason => ReasonEnum,
          :message => String.t() | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.IgnoreCommonModel do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:reason, :struct, MergeAccountingClient.Model.ReasonEnum, options)
  end
end
