# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.Issue do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :status,
    :error_description,
    :end_user,
    :first_incident_time,
    :last_incident_time,
    :is_muted
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :status => MergeAccountingClient.Model.IssueStatusEnum.t() | nil,
          :error_description => String.t(),
          :end_user => %{optional(String.t()) => :any} | nil,
          :first_incident_time => DateTime.t() | nil,
          :last_incident_time => DateTime.t() | nil,
          :is_muted => boolean() | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.Issue do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:status, :struct, MergeAccountingClient.Model.IssueStatusEnum, options)
    |> deserialize(
      :end_user,
      :map,
      MergeAccountingClient.Model.RemoteData,
      Keyword.merge(options, as: :any)
    )
  end
end
