# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.PolicyTypeEnum do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct []

  @type t :: %__MODULE__{}
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.PolicyTypeEnum do
  def decode(value, _options) do
    value
  end
end
