# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.RemoteResponse do
  @moduledoc """
  # The RemoteResponse Object ### Description The `RemoteResponse` object is used to represent information returned from a third-party endpoint.  ### Usage Example View the `RemoteResponse` returned from your `DataPassthrough`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :method,
    :path,
    :status,
    :response,
    :response_headers,
    :headers
  ]

  @type t :: %__MODULE__{
          :method => String.t(),
          :path => String.t(),
          :status => integer(),
          :response => %{optional(String.t()) => :any},
          :response_headers => %{optional(String.t()) => :any} | nil,
          :headers => %{optional(String.t()) => :any} | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.RemoteResponse do
  # import MergeAccountingClient.Deserializer

  def decode(value, _options) do
    value
  end
end
