# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.RemoteData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :path,
    :data
  ]

  @type t :: %__MODULE__{
          :path => String.t(),
          :data => %{optional(String.t()) => :any} | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.RemoteData do
  # import MergeAccountingClient.Deserializer

  def decode(value, _options) do
    value
  end
end
