# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.SyncStatus do
  @moduledoc """
  # The SyncStatus Object ### Description The `SyncStatus` object is used to represent the syncing state of an account  ### Usage Example View the `SyncStatus` for an account to see how recently its models were synced.
  """

  @derive [Poison.Encoder]
  defstruct [
    :model_name,
    :model_id,
    :last_sync_start,
    :next_sync_start,
    :status,
    :is_initial_sync
  ]

  @type t :: %__MODULE__{
          :model_name => String.t(),
          :model_id => String.t(),
          :last_sync_start => DateTime.t(),
          :next_sync_start => DateTime.t(),
          :status => SyncStatusStatusEnum,
          :is_initial_sync => boolean()
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.SyncStatus do
  import MergeAccountingClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:status, :struct, MergeAccountingClient.Model.SyncStatusStatusEnum, options)
  end
end
