# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.ValidationProblemSource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :pointer
  ]

  @type t :: %__MODULE__{
          :pointer => String.t()
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.ValidationProblemSource do
  def decode(value, _options) do
    value
  end
end
