# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Model.WebhookReceiver do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :event,
    :is_active,
    :key
  ]

  @type t :: %__MODULE__{
          :event => String.t(),
          :is_active => boolean(),
          :key => String.t() | nil
        }
end

defimpl Poison.Decoder, for: MergeAccountingClient.Model.WebhookReceiver do
  def decode(value, _options) do
    value
  end
end
