# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Api.DeleteAccount do
  @moduledoc """
  API calls for all endpoints tagged `DeleteAccount`.
  """

  alias MergeAccountingClient.Connection
  import MergeAccountingClient.RequestBuilder

  @doc """
  Delete a linked account.

  ## Parameters

  - connection (MergeAccountingClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your test/production API Key.
  - x_account_token (String.t): Token identifying the end user.
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec delete_account_create(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_account_create(connection, authorization, x_account_token, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/delete-account")
    |> add_param(:headers, :Authorization, authorization)
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      {200, false}
    ])
  end
end
