# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Api.GenerateKey do
  @moduledoc """
  API calls for all endpoints tagged `GenerateKey`.
  """

  alias MergeAccountingClient.Connection
  import MergeAccountingClient.RequestBuilder

  @doc """
  Create a remote key.

  ## Parameters

  - connection (MergeAccountingClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your test/production API Key.
  - generate_remote_key_request (GenerateRemoteKeyRequest):
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, MergeAccountingClient.Model.RemoteKey.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec generate_key_create(
          Tesla.Env.client(),
          String.t(),
          MergeAccountingClient.Model.GenerateRemoteKeyRequest.t(),
          keyword()
        ) :: {:ok, MergeAccountingClient.Model.RemoteKey.t()} | {:error, Tesla.Env.t()}
  def generate_key_create(connection, authorization, generate_remote_key_request, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/generate-key")
    |> add_param(:headers, :Authorization, authorization)
    |> add_param(:body, :body, generate_remote_key_request)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      {200, %MergeAccountingClient.Model.RemoteKey{}}
    ])
  end
end
