# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeAccountingClient.Api.RegenerateKey do
  @moduledoc """
  API calls for all endpoints tagged `RegenerateKey`.
  """

  alias MergeAccountingClient.Connection
  import MergeAccountingClient.RequestBuilder

  @doc """
  Exchange remote keys.

  ## Parameters

  - connection (MergeAccountingClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your test/production API Key.
  - remote_key_for_regeneration_request (RemoteKeyForRegenerationRequest):
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, MergeAccountingClient.Model.RemoteKey.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec regenerate_key_create(
          Tesla.Env.client(),
          String.t(),
          MergeAccountingClient.Model.RemoteKeyForRegenerationRequest.t(),
          keyword()
        ) :: {:ok, MergeAccountingClient.Model.RemoteKey.t()} | {:error, Tesla.Env.t()}
  def regenerate_key_create(
        connection,
        authorization,
        remote_key_for_regeneration_request,
        _opts \\ []
      ) do
    %{}
    |> method(:post)
    |> url("/regenerate-key")
    |> add_param(:headers, :Authorization, authorization)
    |> add_param(:body, :body, remote_key_for_regeneration_request)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      {200, %MergeAccountingClient.Model.RemoteKey{}}
    ])
  end
end
